### ISSUE TITLE
New crate for vhost-user-i2c

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/community#106]
## Crate Name
vhost-user-i2c

## Short Description

This program will be a vhost-user backend that emulates a VirtIO I2C bus. This program takes the layout of the i2c bus and its devices on the host OS and then talks to them via the /dev/i2c-X interface when a request comes from the guest OS for an I2C or SMBUS device.

## Why is this crate relevant to the rust-vmm project?

This is part of a wider initiative by Linaro called "project Stratos" for which you can find information here:
  https://collaborate.linaro.org/display/STR/Stratos+Home

We are looking to implement the backends as a vhost-user device because we want to experiment in making portable backends that can be used with multiple hypervisors.  We also want to support backends isolated in their own separate service VMs with limited memory cross-sections with the principle guest.

And so we are looking to have the same done for I2C with Rust because of the benefits rust provides and rust-vmm is the perfect place to keep it.

I have already implemented the initial support for that, it supports both I2C and SMBUS protocols and is tested with QEMU for now. A detailed email sent to rust-vmm list can be seen here:

https://lore.kernel.org/qemu-devel/20210428122247.ymwshfuoojxzsebf@vireshk-i7/

The crate is here:

https://github.com/vireshk/vhost-user-i2c

Thanks
Viresh Kumar
Linaro Ltd.

**Comment by slp** [comment]
Both the Stratos project and vhost-user-i2c look really interesting. I think it'd be nice to have this crate on rust-vmm.

**Comment by jiangliu** [comment]
The Stratos project sounds interesting, it would be great for rust-vmm to host the vhost-user-i2c. I2C/SMBus is a little weight management bus, it's a little heavy for vhost-user-i2c to map all VM's guest memory. It would be great to constraint the guest memory range to support virtio-i2c, such as preallocating and  registering data buffers used by the virtio-i2c driver?

**Comment by sboeuf** [comment]
Summarizing the rust-vmm community discussion:
- Community is okay with this crate, but it would be part of a common repo (`vhost-device`) in order to get all vhost-user devices grouped together as a common workspace.
- Community won't accept a `vhost-user-i2c` implementation until it is merged in Linux upstream (meaning approval from VIRTIO maintainers).

**Comment by vireshk** [comment]
> Summarizing the rust-vmm community discussion:
> 
> * Community is okay with this crate, but it would be part of a common repo (`vhost-device`) in order to get all vhost-user devices grouped together as a common workspace.

Fair enough. So how should I proceed for that, as I can clearly see that there is no such repository already in place.

> * Community won't accept a `vhost-user-i2c` implementation until it is merged in Linux upstream (meaning approval from VIRTIO maintainers).

The virtio spec is already updated with i2c specs, and the I2C maintainer is going to apply the patch soon, I haven't seen any objection from virtio maintainers for the same.

**Comment by sboeuf** [comment]
>Fair enough. So how should I proceed for that, as I can clearly see that there is no such repository already in place.

I think @andreeaflorescu can follow up on this.

>The virtio spec is already updated with i2c specs, and the I2C maintainer is going to apply the patch soon, I haven't seen any objection from virtio maintainers for the same.

That's really good :)
So I guess it shouldn't take too long to get your patches merged in Linux upstream, right?

**Comment by vireshk** [comment]
> The Stratos project sounds interesting, it would be great for rust-vmm to host the vhost-user-i2c. I2C/SMBus is a little weight management bus, it's a little heavy for vhost-user-i2c to map all VM's guest memory. It would be great to constraint the guest memory range to support virtio-i2c, such as preallocating and registering data buffers used by the virtio-i2c driver?

Thanks for the encouragement. I think there was a discussion around fat-virtqueues for solving the problem you mentioned.

https://projects.linaro.org/browse/STR-15

**Comment by arndb** [comment]
> It would be great to constraint the guest memory range to support virtio-i2c, such as preallocating and 
> registering data buffers used by the virtio-i2c driver?

This issue is separate from the particular virtio protocol on top of the virtio transport. The buffer management is part of the virtqueue implementation that is shared between all virtio devices. I'm working on a prototype for extending the virtqueue spec to support passing all data in a single buffer for both the descriptors and the user data, under the "fat virtqueue" name for the moment. Once I have this working, it should be usable for any virtio device.

**Comment by vireshk** [comment]
> So I guess it shouldn't take too long to get your patches merged in Linux upstream, right?

The Linux patches are from Jie Deng (Intel). Wolfram (I2C maintainer) said that he is going to look at them soon, I hope them to be part of next rc1.

https://lore.kernel.org/linux-i2c/226a8d5663b7bb6f5d06ede7701eedb18d1bafa1.1616493817.git.jie.deng@intel.com/

**Comment by slp** [comment]
>     * Community is okay with this crate, but it would be part of a common repo (`vhost-device`) in order to get all vhost-user devices grouped together as a common workspace.

Is this decision set in stone? Repositories are cheap, what are the advantages of using a single one for all the vhost-user device? Do those advantages overcome the problems (mixed commits, packaging the crate will ship all devices)?

**Comment by andreeaflorescu** [comment]
> > ```
> > * Community is okay with this crate, but it would be part of a common repo (`vhost-device`) in order to get all vhost-user devices grouped together as a common workspace.
> > ```
> 
> Is this decision set in stone? Repositories are cheap, what are the advantages of using a single one for all the vhost-user device? Do those advantages overcome the problems (mixed commits, packaging the crate will ship all devices)?

It's set in stone, it's something that we discussed at the rust-vmm sync meeting, but since not everyone can join, I think decisions taken there can be reverted IMO. We should probably take a more informed decision and balance out the advantages and disadvantages of each approach.

Repositories are not necessarily cheap, they have an associated maintenance cost (which is probably hidden for most people). To give a few examples of things you need to do per repository:
- update the rust-vmm-ci (this one is now taking less time since we switch to dependabot, but people still need to review and update the PRs if needed).
- in case there are non-default features in a crate, we need to create a private buildkite pipeline and update the Buildkite setup.

The mixed commits is also something that I do not like.

Packaging the crate **does not** ship all devices. The devices belong to the same workspace, but they each are published individually on crates.io. For example, let's assume that we have the vhost-device workspace with 3 devices in it (vhost-user-i2c, vhost-user-block, vhost-user-net). Then the vhost-device repository will look as follows:

```
/vhost-device
    Cargo.toml
    /vhost-user-i2c
        /src/
            /src/Cargo.toml
            /src/lib.rs
    /vhost-user-block\
        /src/
            /src/Cargo.toml
            /src/lib.rs
    /vhost-user-network
        /src/
            /src/Cargo.toml
            /src/lib.rs
```

The `Cargo.toml` in the root of the repository is needed such that we can define this repository as a workspace. This will make things like `cargo test` run the tests for all sub-crates in this workspace.

Running `cargo publish` from the root has no effect. If I am not mistaken it might even yield an error. What must happen when we want to publish a crate is that we need to go to the directory corresponding the crate and run `cargo publish`.

I do not feel strongly about either approach (workspace versus separate repositories) in this particular case. I created this issue so we can agree on a path forward: https://github.com/rust-vmm/community/issues/108

**Comment by andreeaflorescu** [comment]
I created the vhost-device repository: https://github.com/rust-vmm/vhost-device

This is created from the template, but the `Cargo.toml` will need to be updated to support rust workspace. @vireshk would you like to do that? If you need help, let me know.

**Comment by andreeaflorescu** [comment]
The discussion is now moved in the [vhost-device repo](https://github.com/rust-vmm/vhost-device/pull/1). Closing this issue.
